json.id                   deputado.id
json.nome                 deputado.nome
json.email                deputado.email
json.partido              deputado.partido
json.uf                   deputado.uf
json.url_foto             deputado.url_foto
json.total_despesas       number_to_currency(deputado.total_despesas)
json.total_votos          deputado.total_votos
json.porcentagem_votos    deputado.porcentagem_votos
json.situacao_candidatura deputado.situacao_candidatura
